//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Eclipse.Sumo.Libtraci {

public class Lane : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Lane(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Lane obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Lane obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Lane() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libtraciPINVOKE.delete_Lane(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static int getLinkNumber(string laneID) {
    int ret = libtraciPINVOKE.Lane_getLinkNumber(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getEdgeID(string laneID) {
    string ret = libtraciPINVOKE.Lane_getEdgeID(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getLength(string laneID) {
    double ret = libtraciPINVOKE.Lane_getLength(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getMaxSpeed(string laneID) {
    double ret = libtraciPINVOKE.Lane_getMaxSpeed(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getFriction(string laneID) {
    double ret = libtraciPINVOKE.Lane_getFriction(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getAllowed(string laneID) {
    StringVector ret = new StringVector(libtraciPINVOKE.Lane_getAllowed(laneID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getDisallowed(string laneID) {
    StringVector ret = new StringVector(libtraciPINVOKE.Lane_getDisallowed(laneID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getChangePermissions(string laneID, int direction) {
    StringVector ret = new StringVector(libtraciPINVOKE.Lane_getChangePermissions(laneID, direction), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCIConnectionVector getLinks(string laneID) {
    TraCIConnectionVector ret = new TraCIConnectionVector(libtraciPINVOKE.Lane_getLinks(laneID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCIPositionVector getShape(string laneID) {
    TraCIPositionVector ret = new TraCIPositionVector(libtraciPINVOKE.Lane_getShape(laneID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getWidth(string laneID) {
    double ret = libtraciPINVOKE.Lane_getWidth(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getCO2Emission(string laneID) {
    double ret = libtraciPINVOKE.Lane_getCO2Emission(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getCOEmission(string laneID) {
    double ret = libtraciPINVOKE.Lane_getCOEmission(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getHCEmission(string laneID) {
    double ret = libtraciPINVOKE.Lane_getHCEmission(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getPMxEmission(string laneID) {
    double ret = libtraciPINVOKE.Lane_getPMxEmission(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getNOxEmission(string laneID) {
    double ret = libtraciPINVOKE.Lane_getNOxEmission(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getFuelConsumption(string laneID) {
    double ret = libtraciPINVOKE.Lane_getFuelConsumption(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getNoiseEmission(string laneID) {
    double ret = libtraciPINVOKE.Lane_getNoiseEmission(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getElectricityConsumption(string laneID) {
    double ret = libtraciPINVOKE.Lane_getElectricityConsumption(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getLastStepMeanSpeed(string laneID) {
    double ret = libtraciPINVOKE.Lane_getLastStepMeanSpeed(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getLastStepOccupancy(string laneID) {
    double ret = libtraciPINVOKE.Lane_getLastStepOccupancy(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getLastStepLength(string laneID) {
    double ret = libtraciPINVOKE.Lane_getLastStepLength(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getWaitingTime(string laneID) {
    double ret = libtraciPINVOKE.Lane_getWaitingTime(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getTraveltime(string laneID) {
    double ret = libtraciPINVOKE.Lane_getTraveltime(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getLastStepVehicleNumber(string laneID) {
    int ret = libtraciPINVOKE.Lane_getLastStepVehicleNumber(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getLastStepHaltingNumber(string laneID) {
    int ret = libtraciPINVOKE.Lane_getLastStepHaltingNumber(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getLastStepVehicleIDs(string laneID) {
    StringVector ret = new StringVector(libtraciPINVOKE.Lane_getLastStepVehicleIDs(laneID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getFoes(string laneID, string toLaneID) {
    StringVector ret = new StringVector(libtraciPINVOKE.Lane_getFoes(laneID, toLaneID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getInternalFoes(string laneID) {
    StringVector ret = new StringVector(libtraciPINVOKE.Lane_getInternalFoes(laneID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getPendingVehicles(string laneID) {
    StringVector ret = new StringVector(libtraciPINVOKE.Lane_getPendingVehicles(laneID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getAngle(string laneID, double relativePosition) {
    double ret = libtraciPINVOKE.Lane_getAngle__SWIG_0(laneID, relativePosition);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getAngle(string laneID) {
    double ret = libtraciPINVOKE.Lane_getAngle__SWIG_1(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getBidiLane(string laneID) {
    string ret = libtraciPINVOKE.Lane_getBidiLane(laneID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getIDList() {
    StringVector ret = new StringVector(libtraciPINVOKE.Lane_getIDList(), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getIDCount() {
    int ret = libtraciPINVOKE.Lane_getIDCount();
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getParameter(string objectID, string key) {
    string ret = libtraciPINVOKE.Lane_getParameter(objectID, key);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringStringPair getParameterWithKey(string objectID, string key) {
    StringStringPair ret = new StringStringPair(libtraciPINVOKE.Lane_getParameterWithKey(objectID, key), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void setParameter(string objectID, string key, string value) {
    libtraciPINVOKE.Lane_setParameter(objectID, key, value);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribe(string objectID, IntVector varIDs, double begin, double end, TraCIResults parameters) {
    libtraciPINVOKE.Lane_subscribe__SWIG_0(objectID, IntVector.getCPtr(varIDs), begin, end, TraCIResults.getCPtr(parameters));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribe(string objectID, IntVector varIDs, double begin, double end) {
    libtraciPINVOKE.Lane_subscribe__SWIG_1(objectID, IntVector.getCPtr(varIDs), begin, end);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribe(string objectID, IntVector varIDs, double begin) {
    libtraciPINVOKE.Lane_subscribe__SWIG_2(objectID, IntVector.getCPtr(varIDs), begin);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribe(string objectID, IntVector varIDs) {
    libtraciPINVOKE.Lane_subscribe__SWIG_3(objectID, IntVector.getCPtr(varIDs));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribe(string objectID) {
    libtraciPINVOKE.Lane_subscribe__SWIG_4(objectID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void unsubscribe(string objectID) {
    libtraciPINVOKE.Lane_unsubscribe(objectID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeContext(string objectID, int domain, double dist, IntVector varIDs, double begin, double end, TraCIResults parameters) {
    libtraciPINVOKE.Lane_subscribeContext__SWIG_0(objectID, domain, dist, IntVector.getCPtr(varIDs), begin, end, TraCIResults.getCPtr(parameters));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeContext(string objectID, int domain, double dist, IntVector varIDs, double begin, double end) {
    libtraciPINVOKE.Lane_subscribeContext__SWIG_1(objectID, domain, dist, IntVector.getCPtr(varIDs), begin, end);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeContext(string objectID, int domain, double dist, IntVector varIDs, double begin) {
    libtraciPINVOKE.Lane_subscribeContext__SWIG_2(objectID, domain, dist, IntVector.getCPtr(varIDs), begin);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeContext(string objectID, int domain, double dist, IntVector varIDs) {
    libtraciPINVOKE.Lane_subscribeContext__SWIG_3(objectID, domain, dist, IntVector.getCPtr(varIDs));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeContext(string objectID, int domain, double dist) {
    libtraciPINVOKE.Lane_subscribeContext__SWIG_4(objectID, domain, dist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void unsubscribeContext(string objectID, int domain, double dist) {
    libtraciPINVOKE.Lane_unsubscribeContext(objectID, domain, dist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SubscriptionResults getAllSubscriptionResults() {
    SubscriptionResults ret = new SubscriptionResults(libtraciPINVOKE.Lane_getAllSubscriptionResults(), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCIResults getSubscriptionResults(string objectID) {
    TraCIResults ret = new TraCIResults(libtraciPINVOKE.Lane_getSubscriptionResults(objectID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ContextSubscriptionResults getAllContextSubscriptionResults() {
    ContextSubscriptionResults ret = new ContextSubscriptionResults(libtraciPINVOKE.Lane_getAllContextSubscriptionResults(), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SubscriptionResults getContextSubscriptionResults(string objectID) {
    SubscriptionResults ret = new SubscriptionResults(libtraciPINVOKE.Lane_getContextSubscriptionResults(objectID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void subscribeParameterWithKey(string objectID, string key, double beginTime, double endTime) {
    libtraciPINVOKE.Lane_subscribeParameterWithKey__SWIG_0(objectID, key, beginTime, endTime);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeParameterWithKey(string objectID, string key, double beginTime) {
    libtraciPINVOKE.Lane_subscribeParameterWithKey__SWIG_1(objectID, key, beginTime);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeParameterWithKey(string objectID, string key) {
    libtraciPINVOKE.Lane_subscribeParameterWithKey__SWIG_2(objectID, key);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static int DOMAIN_ID {
    get {
      int ret = libtraciPINVOKE.Lane_DOMAIN_ID_get();
      if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public static int domainID() {
    int ret = libtraciPINVOKE.Lane_domainID();
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void setAllowed(string laneID, string allowedClasses) {
    libtraciPINVOKE.Lane_setAllowed__SWIG_0(laneID, allowedClasses);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setAllowed(string laneID, StringVector allowedClasses) {
    libtraciPINVOKE.Lane_setAllowed__SWIG_1(laneID, StringVector.getCPtr(allowedClasses));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setDisallowed(string laneID, string disallowedClasses) {
    libtraciPINVOKE.Lane_setDisallowed__SWIG_0(laneID, disallowedClasses);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setDisallowed(string laneID, StringVector disallowedClasses) {
    libtraciPINVOKE.Lane_setDisallowed__SWIG_1(laneID, StringVector.getCPtr(disallowedClasses));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setChangePermissions(string laneID, StringVector allowedClasses, int direction) {
    libtraciPINVOKE.Lane_setChangePermissions(laneID, StringVector.getCPtr(allowedClasses), direction);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setMaxSpeed(string laneID, double speed) {
    libtraciPINVOKE.Lane_setMaxSpeed(laneID, speed);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setLength(string laneID, double length) {
    libtraciPINVOKE.Lane_setLength(laneID, length);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setFriction(string laneID, double friction) {
    libtraciPINVOKE.Lane_setFriction(laneID, friction);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
