//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Eclipse.Sumo.Libtraci {

public class Vehicle : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vehicle(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vehicle obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Vehicle obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Vehicle() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libtraciPINVOKE.delete_Vehicle(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static double getSpeed(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getSpeed(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getLateralSpeed(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getLateralSpeed(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getAcceleration(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getAcceleration(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getSpeedWithoutTraCI(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getSpeedWithoutTraCI(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCIPosition getPosition(string vehID, bool includeZ) {
    TraCIPosition ret = new TraCIPosition(libtraciPINVOKE.Vehicle_getPosition__SWIG_0(vehID, includeZ), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCIPosition getPosition(string vehID) {
    TraCIPosition ret = new TraCIPosition(libtraciPINVOKE.Vehicle_getPosition__SWIG_1(vehID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCIPosition getPosition3D(string vehID) {
    TraCIPosition ret = new TraCIPosition(libtraciPINVOKE.Vehicle_getPosition3D(vehID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getAngle(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getAngle(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getSlope(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getSlope(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getRoadID(string vehID) {
    string ret = libtraciPINVOKE.Vehicle_getRoadID(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getLaneID(string vehID) {
    string ret = libtraciPINVOKE.Vehicle_getLaneID(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getLaneIndex(string vehID) {
    int ret = libtraciPINVOKE.Vehicle_getLaneIndex(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getSegmentID(string vehID) {
    string ret = libtraciPINVOKE.Vehicle_getSegmentID(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getSegmentIndex(string vehID) {
    int ret = libtraciPINVOKE.Vehicle_getSegmentIndex(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getTypeID(string vehID) {
    string ret = libtraciPINVOKE.Vehicle_getTypeID(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getRouteID(string vehID) {
    string ret = libtraciPINVOKE.Vehicle_getRouteID(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getDeparture(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getDeparture(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getDepartDelay(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getDepartDelay(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getRouteIndex(string vehID) {
    int ret = libtraciPINVOKE.Vehicle_getRouteIndex(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getLanePosition(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getLanePosition(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getLateralLanePosition(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getLateralLanePosition(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getCO2Emission(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getCO2Emission(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getCOEmission(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getCOEmission(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getHCEmission(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getHCEmission(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getPMxEmission(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getPMxEmission(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getNOxEmission(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getNOxEmission(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getFuelConsumption(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getFuelConsumption(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getNoiseEmission(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getNoiseEmission(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getElectricityConsumption(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getElectricityConsumption(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getPersonNumber(string vehID) {
    int ret = libtraciPINVOKE.Vehicle_getPersonNumber(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getPersonIDList(string vehID) {
    StringVector ret = new StringVector(libtraciPINVOKE.Vehicle_getPersonIDList(vehID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringDoublePair getLeader(string vehID, double dist) {
    StringDoublePair ret = new StringDoublePair(libtraciPINVOKE.Vehicle_getLeader__SWIG_0(vehID, dist), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringDoublePair getLeader(string vehID) {
    StringDoublePair ret = new StringDoublePair(libtraciPINVOKE.Vehicle_getLeader__SWIG_1(vehID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringDoublePair getFollower(string vehID, double dist) {
    StringDoublePair ret = new StringDoublePair(libtraciPINVOKE.Vehicle_getFollower__SWIG_0(vehID, dist), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringDoublePair getFollower(string vehID) {
    StringDoublePair ret = new StringDoublePair(libtraciPINVOKE.Vehicle_getFollower__SWIG_1(vehID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCIJunctionFoeVector getJunctionFoes(string vehID, double dist) {
    TraCIJunctionFoeVector ret = new TraCIJunctionFoeVector(libtraciPINVOKE.Vehicle_getJunctionFoes__SWIG_0(vehID, dist), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCIJunctionFoeVector getJunctionFoes(string vehID) {
    TraCIJunctionFoeVector ret = new TraCIJunctionFoeVector(libtraciPINVOKE.Vehicle_getJunctionFoes__SWIG_1(vehID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getWaitingTime(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getWaitingTime(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getAccumulatedWaitingTime(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getAccumulatedWaitingTime(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getAdaptedTraveltime(string vehID, double time, string edgeID) {
    double ret = libtraciPINVOKE.Vehicle_getAdaptedTraveltime(vehID, time, edgeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getEffort(string vehID, double time, string edgeID) {
    double ret = libtraciPINVOKE.Vehicle_getEffort(vehID, time, edgeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool isRouteValid(string vehID) {
    bool ret = libtraciPINVOKE.Vehicle_isRouteValid(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getRoute(string vehID) {
    StringVector ret = new StringVector(libtraciPINVOKE.Vehicle_getRoute(vehID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getSignals(string vehID) {
    int ret = libtraciPINVOKE.Vehicle_getSignals(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCIBestLanesDataVector getBestLanes(string vehID) {
    TraCIBestLanesDataVector ret = new TraCIBestLanesDataVector(libtraciPINVOKE.Vehicle_getBestLanes(vehID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCINextTLSVector getNextTLS(string vehID) {
    TraCINextTLSVector ret = new TraCINextTLSVector(libtraciPINVOKE.Vehicle_getNextTLS(vehID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCINextStopDataVector getNextStops(string vehID) {
    TraCINextStopDataVector ret = new TraCINextStopDataVector(libtraciPINVOKE.Vehicle_getNextStops(vehID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCIConnectionVector getNextLinks(string vehID) {
    TraCIConnectionVector ret = new TraCIConnectionVector(libtraciPINVOKE.Vehicle_getNextLinks(vehID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCINextStopDataVector getStops(string vehID, int limit) {
    TraCINextStopDataVector ret = new TraCINextStopDataVector(libtraciPINVOKE.Vehicle_getStops__SWIG_0(vehID, limit), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCINextStopDataVector getStops(string vehID) {
    TraCINextStopDataVector ret = new TraCINextStopDataVector(libtraciPINVOKE.Vehicle_getStops__SWIG_1(vehID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getStopState(string vehID) {
    int ret = libtraciPINVOKE.Vehicle_getStopState(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getStopParameter(string vehID, int nextStopIndex, string param, bool customParam) {
    string ret = libtraciPINVOKE.Vehicle_getStopParameter__SWIG_0(vehID, nextStopIndex, param, customParam);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getStopParameter(string vehID, int nextStopIndex, string param) {
    string ret = libtraciPINVOKE.Vehicle_getStopParameter__SWIG_1(vehID, nextStopIndex, param);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getDistance(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getDistance(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getDrivingDistance(string vehID, string edgeID, double pos, int laneIndex) {
    double ret = libtraciPINVOKE.Vehicle_getDrivingDistance__SWIG_0(vehID, edgeID, pos, laneIndex);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getDrivingDistance(string vehID, string edgeID, double pos) {
    double ret = libtraciPINVOKE.Vehicle_getDrivingDistance__SWIG_1(vehID, edgeID, pos);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getDrivingDistance2D(string vehID, double x, double y) {
    double ret = libtraciPINVOKE.Vehicle_getDrivingDistance2D(vehID, x, y);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getAllowedSpeed(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getAllowedSpeed(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getSpeedMode(string vehID) {
    int ret = libtraciPINVOKE.Vehicle_getSpeedMode(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getLaneChangeMode(string vehID) {
    int ret = libtraciPINVOKE.Vehicle_getLaneChangeMode(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getRoutingMode(string vehID) {
    int ret = libtraciPINVOKE.Vehicle_getRoutingMode(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getLine(string vehID) {
    string ret = libtraciPINVOKE.Vehicle_getLine(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getVia(string vehID) {
    StringVector ret = new StringVector(libtraciPINVOKE.Vehicle_getVia(vehID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static IntIntPair getLaneChangeState(string vehID, int direction) {
    IntIntPair ret = new IntIntPair(libtraciPINVOKE.Vehicle_getLaneChangeState(vehID, direction), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getLastActionTime(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getLastActionTime(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringDoublePairVector getNeighbors(string vehID, int mode) {
    StringDoublePairVector ret = new StringDoublePairVector(libtraciPINVOKE.Vehicle_getNeighbors(vehID, mode), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getFollowSpeed(string vehID, double speed, double gap, double leaderSpeed, double leaderMaxDecel, string leaderID) {
    double ret = libtraciPINVOKE.Vehicle_getFollowSpeed__SWIG_0(vehID, speed, gap, leaderSpeed, leaderMaxDecel, leaderID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getFollowSpeed(string vehID, double speed, double gap, double leaderSpeed, double leaderMaxDecel) {
    double ret = libtraciPINVOKE.Vehicle_getFollowSpeed__SWIG_1(vehID, speed, gap, leaderSpeed, leaderMaxDecel);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getSecureGap(string vehID, double speed, double leaderSpeed, double leaderMaxDecel, string leaderID) {
    double ret = libtraciPINVOKE.Vehicle_getSecureGap__SWIG_0(vehID, speed, leaderSpeed, leaderMaxDecel, leaderID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getSecureGap(string vehID, double speed, double leaderSpeed, double leaderMaxDecel) {
    double ret = libtraciPINVOKE.Vehicle_getSecureGap__SWIG_1(vehID, speed, leaderSpeed, leaderMaxDecel);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getStopSpeed(string vehID, double speed, double gap) {
    double ret = libtraciPINVOKE.Vehicle_getStopSpeed(vehID, speed, gap);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getStopDelay(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getStopDelay(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getStopArrivalDelay(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getStopArrivalDelay(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getTimeLoss(string vehID) {
    double ret = libtraciPINVOKE.Vehicle_getTimeLoss(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getTaxiFleet(int taxiState) {
    StringVector ret = new StringVector(libtraciPINVOKE.Vehicle_getTaxiFleet__SWIG_0(taxiState), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getTaxiFleet() {
    StringVector ret = new StringVector(libtraciPINVOKE.Vehicle_getTaxiFleet__SWIG_1(), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getLoadedIDList() {
    StringVector ret = new StringVector(libtraciPINVOKE.Vehicle_getLoadedIDList(), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getTeleportingIDList() {
    StringVector ret = new StringVector(libtraciPINVOKE.Vehicle_getTeleportingIDList(), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringVector getIDList() {
    StringVector ret = new StringVector(libtraciPINVOKE.Vehicle_getIDList(), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getIDCount() {
    int ret = libtraciPINVOKE.Vehicle_getIDCount();
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getParameter(string objectID, string key) {
    string ret = libtraciPINVOKE.Vehicle_getParameter(objectID, key);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static StringStringPair getParameterWithKey(string objectID, string key) {
    StringStringPair ret = new StringStringPair(libtraciPINVOKE.Vehicle_getParameterWithKey(objectID, key), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void setParameter(string objectID, string key, string value) {
    libtraciPINVOKE.Vehicle_setParameter(objectID, key, value);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static double getLength(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getLength(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getMaxSpeed(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getMaxSpeed(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getVehicleClass(string typeID) {
    string ret = libtraciPINVOKE.Vehicle_getVehicleClass(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getSpeedFactor(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getSpeedFactor(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getAccel(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getAccel(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getDecel(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getDecel(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getEmergencyDecel(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getEmergencyDecel(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getApparentDecel(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getApparentDecel(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getImperfection(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getImperfection(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getTau(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getTau(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getEmissionClass(string typeID) {
    string ret = libtraciPINVOKE.Vehicle_getEmissionClass(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getShapeClass(string typeID) {
    string ret = libtraciPINVOKE.Vehicle_getShapeClass(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getMinGap(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getMinGap(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getWidth(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getWidth(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getHeight(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getHeight(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getMass(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getMass(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCIColor getColor(string typeID) {
    TraCIColor ret = new TraCIColor(libtraciPINVOKE.Vehicle_getColor(typeID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getMinGapLat(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getMinGapLat(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getMaxSpeedLat(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getMaxSpeedLat(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string getLateralAlignment(string typeID) {
    string ret = libtraciPINVOKE.Vehicle_getLateralAlignment(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getPersonCapacity(string typeID) {
    int ret = libtraciPINVOKE.Vehicle_getPersonCapacity(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getActionStepLength(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getActionStepLength(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getSpeedDeviation(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getSpeedDeviation(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getBoardingDuration(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getBoardingDuration(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static double getImpatience(string typeID) {
    double ret = libtraciPINVOKE.Vehicle_getImpatience(typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void setStop(string vehID, string edgeID, double pos, int laneIndex, double duration, int flags, double startPos, double until) {
    libtraciPINVOKE.Vehicle_setStop__SWIG_0(vehID, edgeID, pos, laneIndex, duration, flags, startPos, until);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setStop(string vehID, string edgeID, double pos, int laneIndex, double duration, int flags, double startPos) {
    libtraciPINVOKE.Vehicle_setStop__SWIG_1(vehID, edgeID, pos, laneIndex, duration, flags, startPos);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setStop(string vehID, string edgeID, double pos, int laneIndex, double duration, int flags) {
    libtraciPINVOKE.Vehicle_setStop__SWIG_2(vehID, edgeID, pos, laneIndex, duration, flags);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setStop(string vehID, string edgeID, double pos, int laneIndex, double duration) {
    libtraciPINVOKE.Vehicle_setStop__SWIG_3(vehID, edgeID, pos, laneIndex, duration);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setStop(string vehID, string edgeID, double pos, int laneIndex) {
    libtraciPINVOKE.Vehicle_setStop__SWIG_4(vehID, edgeID, pos, laneIndex);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setStop(string vehID, string edgeID, double pos) {
    libtraciPINVOKE.Vehicle_setStop__SWIG_5(vehID, edgeID, pos);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setStop(string vehID, string edgeID) {
    libtraciPINVOKE.Vehicle_setStop__SWIG_6(vehID, edgeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void replaceStop(string vehID, int nextStopIndex, string edgeID, double pos, int laneIndex, double duration, int flags, double startPos, double until, int teleport) {
    libtraciPINVOKE.Vehicle_replaceStop__SWIG_0(vehID, nextStopIndex, edgeID, pos, laneIndex, duration, flags, startPos, until, teleport);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void replaceStop(string vehID, int nextStopIndex, string edgeID, double pos, int laneIndex, double duration, int flags, double startPos, double until) {
    libtraciPINVOKE.Vehicle_replaceStop__SWIG_1(vehID, nextStopIndex, edgeID, pos, laneIndex, duration, flags, startPos, until);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void replaceStop(string vehID, int nextStopIndex, string edgeID, double pos, int laneIndex, double duration, int flags, double startPos) {
    libtraciPINVOKE.Vehicle_replaceStop__SWIG_2(vehID, nextStopIndex, edgeID, pos, laneIndex, duration, flags, startPos);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void replaceStop(string vehID, int nextStopIndex, string edgeID, double pos, int laneIndex, double duration, int flags) {
    libtraciPINVOKE.Vehicle_replaceStop__SWIG_3(vehID, nextStopIndex, edgeID, pos, laneIndex, duration, flags);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void replaceStop(string vehID, int nextStopIndex, string edgeID, double pos, int laneIndex, double duration) {
    libtraciPINVOKE.Vehicle_replaceStop__SWIG_4(vehID, nextStopIndex, edgeID, pos, laneIndex, duration);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void replaceStop(string vehID, int nextStopIndex, string edgeID, double pos, int laneIndex) {
    libtraciPINVOKE.Vehicle_replaceStop__SWIG_5(vehID, nextStopIndex, edgeID, pos, laneIndex);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void replaceStop(string vehID, int nextStopIndex, string edgeID, double pos) {
    libtraciPINVOKE.Vehicle_replaceStop__SWIG_6(vehID, nextStopIndex, edgeID, pos);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void replaceStop(string vehID, int nextStopIndex, string edgeID) {
    libtraciPINVOKE.Vehicle_replaceStop__SWIG_7(vehID, nextStopIndex, edgeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void insertStop(string vehID, int nextStopIndex, string edgeID, double pos, int laneIndex, double duration, int flags, double startPos, double until, int teleport) {
    libtraciPINVOKE.Vehicle_insertStop__SWIG_0(vehID, nextStopIndex, edgeID, pos, laneIndex, duration, flags, startPos, until, teleport);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void insertStop(string vehID, int nextStopIndex, string edgeID, double pos, int laneIndex, double duration, int flags, double startPos, double until) {
    libtraciPINVOKE.Vehicle_insertStop__SWIG_1(vehID, nextStopIndex, edgeID, pos, laneIndex, duration, flags, startPos, until);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void insertStop(string vehID, int nextStopIndex, string edgeID, double pos, int laneIndex, double duration, int flags, double startPos) {
    libtraciPINVOKE.Vehicle_insertStop__SWIG_2(vehID, nextStopIndex, edgeID, pos, laneIndex, duration, flags, startPos);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void insertStop(string vehID, int nextStopIndex, string edgeID, double pos, int laneIndex, double duration, int flags) {
    libtraciPINVOKE.Vehicle_insertStop__SWIG_3(vehID, nextStopIndex, edgeID, pos, laneIndex, duration, flags);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void insertStop(string vehID, int nextStopIndex, string edgeID, double pos, int laneIndex, double duration) {
    libtraciPINVOKE.Vehicle_insertStop__SWIG_4(vehID, nextStopIndex, edgeID, pos, laneIndex, duration);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void insertStop(string vehID, int nextStopIndex, string edgeID, double pos, int laneIndex) {
    libtraciPINVOKE.Vehicle_insertStop__SWIG_5(vehID, nextStopIndex, edgeID, pos, laneIndex);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void insertStop(string vehID, int nextStopIndex, string edgeID, double pos) {
    libtraciPINVOKE.Vehicle_insertStop__SWIG_6(vehID, nextStopIndex, edgeID, pos);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void insertStop(string vehID, int nextStopIndex, string edgeID) {
    libtraciPINVOKE.Vehicle_insertStop__SWIG_7(vehID, nextStopIndex, edgeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setStopParameter(string vehID, int nextStopIndex, string param, string value, bool customParam) {
    libtraciPINVOKE.Vehicle_setStopParameter__SWIG_0(vehID, nextStopIndex, param, value, customParam);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setStopParameter(string vehID, int nextStopIndex, string param, string value) {
    libtraciPINVOKE.Vehicle_setStopParameter__SWIG_1(vehID, nextStopIndex, param, value);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void rerouteParkingArea(string vehID, string parkingAreaID) {
    libtraciPINVOKE.Vehicle_rerouteParkingArea(vehID, parkingAreaID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void resume(string vehID) {
    libtraciPINVOKE.Vehicle_resume(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID, string typeID, string depart, string departLane, string departPos, string departSpeed, string arrivalLane, string arrivalPos, string arrivalSpeed, string fromTaz, string toTaz, string line, int personCapacity, int personNumber) {
    libtraciPINVOKE.Vehicle_add__SWIG_0(vehID, routeID, typeID, depart, departLane, departPos, departSpeed, arrivalLane, arrivalPos, arrivalSpeed, fromTaz, toTaz, line, personCapacity, personNumber);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID, string typeID, string depart, string departLane, string departPos, string departSpeed, string arrivalLane, string arrivalPos, string arrivalSpeed, string fromTaz, string toTaz, string line, int personCapacity) {
    libtraciPINVOKE.Vehicle_add__SWIG_1(vehID, routeID, typeID, depart, departLane, departPos, departSpeed, arrivalLane, arrivalPos, arrivalSpeed, fromTaz, toTaz, line, personCapacity);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID, string typeID, string depart, string departLane, string departPos, string departSpeed, string arrivalLane, string arrivalPos, string arrivalSpeed, string fromTaz, string toTaz, string line) {
    libtraciPINVOKE.Vehicle_add__SWIG_2(vehID, routeID, typeID, depart, departLane, departPos, departSpeed, arrivalLane, arrivalPos, arrivalSpeed, fromTaz, toTaz, line);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID, string typeID, string depart, string departLane, string departPos, string departSpeed, string arrivalLane, string arrivalPos, string arrivalSpeed, string fromTaz, string toTaz) {
    libtraciPINVOKE.Vehicle_add__SWIG_3(vehID, routeID, typeID, depart, departLane, departPos, departSpeed, arrivalLane, arrivalPos, arrivalSpeed, fromTaz, toTaz);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID, string typeID, string depart, string departLane, string departPos, string departSpeed, string arrivalLane, string arrivalPos, string arrivalSpeed, string fromTaz) {
    libtraciPINVOKE.Vehicle_add__SWIG_4(vehID, routeID, typeID, depart, departLane, departPos, departSpeed, arrivalLane, arrivalPos, arrivalSpeed, fromTaz);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID, string typeID, string depart, string departLane, string departPos, string departSpeed, string arrivalLane, string arrivalPos, string arrivalSpeed) {
    libtraciPINVOKE.Vehicle_add__SWIG_5(vehID, routeID, typeID, depart, departLane, departPos, departSpeed, arrivalLane, arrivalPos, arrivalSpeed);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID, string typeID, string depart, string departLane, string departPos, string departSpeed, string arrivalLane, string arrivalPos) {
    libtraciPINVOKE.Vehicle_add__SWIG_6(vehID, routeID, typeID, depart, departLane, departPos, departSpeed, arrivalLane, arrivalPos);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID, string typeID, string depart, string departLane, string departPos, string departSpeed, string arrivalLane) {
    libtraciPINVOKE.Vehicle_add__SWIG_7(vehID, routeID, typeID, depart, departLane, departPos, departSpeed, arrivalLane);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID, string typeID, string depart, string departLane, string departPos, string departSpeed) {
    libtraciPINVOKE.Vehicle_add__SWIG_8(vehID, routeID, typeID, depart, departLane, departPos, departSpeed);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID, string typeID, string depart, string departLane, string departPos) {
    libtraciPINVOKE.Vehicle_add__SWIG_9(vehID, routeID, typeID, depart, departLane, departPos);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID, string typeID, string depart, string departLane) {
    libtraciPINVOKE.Vehicle_add__SWIG_10(vehID, routeID, typeID, depart, departLane);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID, string typeID, string depart) {
    libtraciPINVOKE.Vehicle_add__SWIG_11(vehID, routeID, typeID, depart);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID, string typeID) {
    libtraciPINVOKE.Vehicle_add__SWIG_12(vehID, routeID, typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void add(string vehID, string routeID) {
    libtraciPINVOKE.Vehicle_add__SWIG_13(vehID, routeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void changeTarget(string vehID, string edgeID) {
    libtraciPINVOKE.Vehicle_changeTarget(vehID, edgeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void changeLane(string vehID, int laneIndex, double duration) {
    libtraciPINVOKE.Vehicle_changeLane(vehID, laneIndex, duration);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void changeLaneRelative(string vehID, int indexOffset, double duration) {
    libtraciPINVOKE.Vehicle_changeLaneRelative(vehID, indexOffset, duration);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void changeSublane(string vehID, double latDist) {
    libtraciPINVOKE.Vehicle_changeSublane(vehID, latDist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void slowDown(string vehID, double speed, double duration) {
    libtraciPINVOKE.Vehicle_slowDown(vehID, speed, duration);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void openGap(string vehID, double newTimeHeadway, double newSpaceHeadway, double duration, double changeRate, double maxDecel, string referenceVehID) {
    libtraciPINVOKE.Vehicle_openGap__SWIG_0(vehID, newTimeHeadway, newSpaceHeadway, duration, changeRate, maxDecel, referenceVehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void openGap(string vehID, double newTimeHeadway, double newSpaceHeadway, double duration, double changeRate, double maxDecel) {
    libtraciPINVOKE.Vehicle_openGap__SWIG_1(vehID, newTimeHeadway, newSpaceHeadway, duration, changeRate, maxDecel);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void openGap(string vehID, double newTimeHeadway, double newSpaceHeadway, double duration, double changeRate) {
    libtraciPINVOKE.Vehicle_openGap__SWIG_2(vehID, newTimeHeadway, newSpaceHeadway, duration, changeRate);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void deactivateGapControl(string vehID) {
    libtraciPINVOKE.Vehicle_deactivateGapControl(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void requestToC(string vehID, double leadTime) {
    libtraciPINVOKE.Vehicle_requestToC(vehID, leadTime);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setSpeed(string vehID, double speed) {
    libtraciPINVOKE.Vehicle_setSpeed(vehID, speed);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setAcceleration(string vehID, double acceleration, double duration) {
    libtraciPINVOKE.Vehicle_setAcceleration(vehID, acceleration, duration);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setPreviousSpeed(string vehID, double prevSpeed, double prevAcceleration) {
    libtraciPINVOKE.Vehicle_setPreviousSpeed__SWIG_0(vehID, prevSpeed, prevAcceleration);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setPreviousSpeed(string vehID, double prevSpeed) {
    libtraciPINVOKE.Vehicle_setPreviousSpeed__SWIG_1(vehID, prevSpeed);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setSpeedMode(string vehID, int speedMode) {
    libtraciPINVOKE.Vehicle_setSpeedMode(vehID, speedMode);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setLaneChangeMode(string vehID, int laneChangeMode) {
    libtraciPINVOKE.Vehicle_setLaneChangeMode(vehID, laneChangeMode);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setRoutingMode(string vehID, int routingMode) {
    libtraciPINVOKE.Vehicle_setRoutingMode(vehID, routingMode);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setType(string vehID, string typeID) {
    libtraciPINVOKE.Vehicle_setType(vehID, typeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setRouteID(string vehID, string routeID) {
    libtraciPINVOKE.Vehicle_setRouteID(vehID, routeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setRoute(string vehID, string edgeID) {
    libtraciPINVOKE.Vehicle_setRoute__SWIG_0(vehID, edgeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setRoute(string vehID, StringVector edgeIDs) {
    libtraciPINVOKE.Vehicle_setRoute__SWIG_1(vehID, StringVector.getCPtr(edgeIDs));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setLateralLanePosition(string vehID, double posLat) {
    libtraciPINVOKE.Vehicle_setLateralLanePosition(vehID, posLat);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void updateBestLanes(string vehID) {
    libtraciPINVOKE.Vehicle_updateBestLanes(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setAdaptedTraveltime(string vehID, string edgeID, double time, double begSeconds, double endSeconds) {
    libtraciPINVOKE.Vehicle_setAdaptedTraveltime__SWIG_0(vehID, edgeID, time, begSeconds, endSeconds);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setAdaptedTraveltime(string vehID, string edgeID, double time, double begSeconds) {
    libtraciPINVOKE.Vehicle_setAdaptedTraveltime__SWIG_1(vehID, edgeID, time, begSeconds);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setAdaptedTraveltime(string vehID, string edgeID, double time) {
    libtraciPINVOKE.Vehicle_setAdaptedTraveltime__SWIG_2(vehID, edgeID, time);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setAdaptedTraveltime(string vehID, string edgeID) {
    libtraciPINVOKE.Vehicle_setAdaptedTraveltime__SWIG_3(vehID, edgeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setEffort(string vehID, string edgeID, double effort, double begSeconds, double endSeconds) {
    libtraciPINVOKE.Vehicle_setEffort__SWIG_0(vehID, edgeID, effort, begSeconds, endSeconds);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setEffort(string vehID, string edgeID, double effort, double begSeconds) {
    libtraciPINVOKE.Vehicle_setEffort__SWIG_1(vehID, edgeID, effort, begSeconds);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setEffort(string vehID, string edgeID, double effort) {
    libtraciPINVOKE.Vehicle_setEffort__SWIG_2(vehID, edgeID, effort);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setEffort(string vehID, string edgeID) {
    libtraciPINVOKE.Vehicle_setEffort__SWIG_3(vehID, edgeID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void rerouteTraveltime(string vehID, bool currentTravelTimes) {
    libtraciPINVOKE.Vehicle_rerouteTraveltime__SWIG_0(vehID, currentTravelTimes);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void rerouteTraveltime(string vehID) {
    libtraciPINVOKE.Vehicle_rerouteTraveltime__SWIG_1(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void rerouteEffort(string vehID) {
    libtraciPINVOKE.Vehicle_rerouteEffort(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setSignals(string vehID, int signals) {
    libtraciPINVOKE.Vehicle_setSignals(vehID, signals);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void moveTo(string vehID, string laneID, double pos, int reason) {
    libtraciPINVOKE.Vehicle_moveTo__SWIG_0(vehID, laneID, pos, reason);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void moveTo(string vehID, string laneID, double pos) {
    libtraciPINVOKE.Vehicle_moveTo__SWIG_1(vehID, laneID, pos);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void moveToXY(string vehID, string edgeID, int laneIndex, double x, double y, double angle, int keepRoute, double matchThreshold) {
    libtraciPINVOKE.Vehicle_moveToXY__SWIG_0(vehID, edgeID, laneIndex, x, y, angle, keepRoute, matchThreshold);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void moveToXY(string vehID, string edgeID, int laneIndex, double x, double y, double angle, int keepRoute) {
    libtraciPINVOKE.Vehicle_moveToXY__SWIG_1(vehID, edgeID, laneIndex, x, y, angle, keepRoute);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void moveToXY(string vehID, string edgeID, int laneIndex, double x, double y, double angle) {
    libtraciPINVOKE.Vehicle_moveToXY__SWIG_2(vehID, edgeID, laneIndex, x, y, angle);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void moveToXY(string vehID, string edgeID, int laneIndex, double x, double y) {
    libtraciPINVOKE.Vehicle_moveToXY__SWIG_3(vehID, edgeID, laneIndex, x, y);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void remove(string vehID, char reason) {
    libtraciPINVOKE.Vehicle_remove__SWIG_0(vehID, reason);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void remove(string vehID) {
    libtraciPINVOKE.Vehicle_remove__SWIG_1(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setLine(string vehID, string line) {
    libtraciPINVOKE.Vehicle_setLine(vehID, line);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setVia(string vehID, StringVector edgeList) {
    libtraciPINVOKE.Vehicle_setVia(vehID, StringVector.getCPtr(edgeList));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void highlight(string vehID, TraCIColor col, double size, int alphaMax, double duration, int type) {
    libtraciPINVOKE.Vehicle_highlight__SWIG_0(vehID, TraCIColor.getCPtr(col), size, alphaMax, duration, type);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void highlight(string vehID, TraCIColor col, double size, int alphaMax, double duration) {
    libtraciPINVOKE.Vehicle_highlight__SWIG_1(vehID, TraCIColor.getCPtr(col), size, alphaMax, duration);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void highlight(string vehID, TraCIColor col, double size, int alphaMax) {
    libtraciPINVOKE.Vehicle_highlight__SWIG_2(vehID, TraCIColor.getCPtr(col), size, alphaMax);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void highlight(string vehID, TraCIColor col, double size) {
    libtraciPINVOKE.Vehicle_highlight__SWIG_3(vehID, TraCIColor.getCPtr(col), size);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void highlight(string vehID, TraCIColor col) {
    libtraciPINVOKE.Vehicle_highlight__SWIG_4(vehID, TraCIColor.getCPtr(col));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void highlight(string vehID) {
    libtraciPINVOKE.Vehicle_highlight__SWIG_5(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void dispatchTaxi(string vehID, StringVector reservations) {
    libtraciPINVOKE.Vehicle_dispatchTaxi(vehID, StringVector.getCPtr(reservations));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setLength(string typeID, double length) {
    libtraciPINVOKE.Vehicle_setLength(typeID, length);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setMaxSpeed(string typeID, double speed) {
    libtraciPINVOKE.Vehicle_setMaxSpeed(typeID, speed);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setVehicleClass(string typeID, string clazz) {
    libtraciPINVOKE.Vehicle_setVehicleClass(typeID, clazz);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setSpeedFactor(string typeID, double factor) {
    libtraciPINVOKE.Vehicle_setSpeedFactor(typeID, factor);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setAccel(string typeID, double accel) {
    libtraciPINVOKE.Vehicle_setAccel(typeID, accel);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setDecel(string typeID, double decel) {
    libtraciPINVOKE.Vehicle_setDecel(typeID, decel);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setEmergencyDecel(string typeID, double decel) {
    libtraciPINVOKE.Vehicle_setEmergencyDecel(typeID, decel);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setApparentDecel(string typeID, double decel) {
    libtraciPINVOKE.Vehicle_setApparentDecel(typeID, decel);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setImperfection(string typeID, double imperfection) {
    libtraciPINVOKE.Vehicle_setImperfection(typeID, imperfection);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setTau(string typeID, double tau) {
    libtraciPINVOKE.Vehicle_setTau(typeID, tau);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setEmissionClass(string typeID, string clazz) {
    libtraciPINVOKE.Vehicle_setEmissionClass(typeID, clazz);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setShapeClass(string typeID, string shapeClass) {
    libtraciPINVOKE.Vehicle_setShapeClass(typeID, shapeClass);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setWidth(string typeID, double width) {
    libtraciPINVOKE.Vehicle_setWidth(typeID, width);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setHeight(string typeID, double height) {
    libtraciPINVOKE.Vehicle_setHeight(typeID, height);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setMass(string typeID, double mass) {
    libtraciPINVOKE.Vehicle_setMass(typeID, mass);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setColor(string typeID, TraCIColor color) {
    libtraciPINVOKE.Vehicle_setColor(typeID, TraCIColor.getCPtr(color));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setMinGap(string typeID, double minGap) {
    libtraciPINVOKE.Vehicle_setMinGap(typeID, minGap);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setMinGapLat(string typeID, double minGapLat) {
    libtraciPINVOKE.Vehicle_setMinGapLat(typeID, minGapLat);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setMaxSpeedLat(string typeID, double speed) {
    libtraciPINVOKE.Vehicle_setMaxSpeedLat(typeID, speed);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setLateralAlignment(string typeID, string latAlignment) {
    libtraciPINVOKE.Vehicle_setLateralAlignment(typeID, latAlignment);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setActionStepLength(string typeID, double actionStepLength, bool resetActionOffset) {
    libtraciPINVOKE.Vehicle_setActionStepLength__SWIG_0(typeID, actionStepLength, resetActionOffset);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setActionStepLength(string typeID, double actionStepLength) {
    libtraciPINVOKE.Vehicle_setActionStepLength__SWIG_1(typeID, actionStepLength);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setBoardingDuration(string typeID, double boardingDuration) {
    libtraciPINVOKE.Vehicle_setBoardingDuration(typeID, boardingDuration);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setImpatience(string typeID, double impatience) {
    libtraciPINVOKE.Vehicle_setImpatience(typeID, impatience);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribe(string objectID, IntVector varIDs, double begin, double end, TraCIResults parameters) {
    libtraciPINVOKE.Vehicle_subscribe__SWIG_0(objectID, IntVector.getCPtr(varIDs), begin, end, TraCIResults.getCPtr(parameters));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribe(string objectID, IntVector varIDs, double begin, double end) {
    libtraciPINVOKE.Vehicle_subscribe__SWIG_1(objectID, IntVector.getCPtr(varIDs), begin, end);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribe(string objectID, IntVector varIDs, double begin) {
    libtraciPINVOKE.Vehicle_subscribe__SWIG_2(objectID, IntVector.getCPtr(varIDs), begin);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribe(string objectID, IntVector varIDs) {
    libtraciPINVOKE.Vehicle_subscribe__SWIG_3(objectID, IntVector.getCPtr(varIDs));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribe(string objectID) {
    libtraciPINVOKE.Vehicle_subscribe__SWIG_4(objectID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void unsubscribe(string objectID) {
    libtraciPINVOKE.Vehicle_unsubscribe(objectID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeContext(string objectID, int domain, double dist, IntVector varIDs, double begin, double end, TraCIResults parameters) {
    libtraciPINVOKE.Vehicle_subscribeContext__SWIG_0(objectID, domain, dist, IntVector.getCPtr(varIDs), begin, end, TraCIResults.getCPtr(parameters));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeContext(string objectID, int domain, double dist, IntVector varIDs, double begin, double end) {
    libtraciPINVOKE.Vehicle_subscribeContext__SWIG_1(objectID, domain, dist, IntVector.getCPtr(varIDs), begin, end);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeContext(string objectID, int domain, double dist, IntVector varIDs, double begin) {
    libtraciPINVOKE.Vehicle_subscribeContext__SWIG_2(objectID, domain, dist, IntVector.getCPtr(varIDs), begin);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeContext(string objectID, int domain, double dist, IntVector varIDs) {
    libtraciPINVOKE.Vehicle_subscribeContext__SWIG_3(objectID, domain, dist, IntVector.getCPtr(varIDs));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeContext(string objectID, int domain, double dist) {
    libtraciPINVOKE.Vehicle_subscribeContext__SWIG_4(objectID, domain, dist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void unsubscribeContext(string objectID, int domain, double dist) {
    libtraciPINVOKE.Vehicle_unsubscribeContext(objectID, domain, dist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SubscriptionResults getAllSubscriptionResults() {
    SubscriptionResults ret = new SubscriptionResults(libtraciPINVOKE.Vehicle_getAllSubscriptionResults(), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TraCIResults getSubscriptionResults(string objectID) {
    TraCIResults ret = new TraCIResults(libtraciPINVOKE.Vehicle_getSubscriptionResults(objectID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ContextSubscriptionResults getAllContextSubscriptionResults() {
    ContextSubscriptionResults ret = new ContextSubscriptionResults(libtraciPINVOKE.Vehicle_getAllContextSubscriptionResults(), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SubscriptionResults getContextSubscriptionResults(string objectID) {
    SubscriptionResults ret = new SubscriptionResults(libtraciPINVOKE.Vehicle_getContextSubscriptionResults(objectID), true);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void subscribeParameterWithKey(string objectID, string key, double beginTime, double endTime) {
    libtraciPINVOKE.Vehicle_subscribeParameterWithKey__SWIG_0(objectID, key, beginTime, endTime);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeParameterWithKey(string objectID, string key, double beginTime) {
    libtraciPINVOKE.Vehicle_subscribeParameterWithKey__SWIG_1(objectID, key, beginTime);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeParameterWithKey(string objectID, string key) {
    libtraciPINVOKE.Vehicle_subscribeParameterWithKey__SWIG_2(objectID, key);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static int DOMAIN_ID {
    get {
      int ret = libtraciPINVOKE.Vehicle_DOMAIN_ID_get();
      if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public static int domainID() {
    int ret = libtraciPINVOKE.Vehicle_domainID();
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void subscribeLeader(string vehID, double dist, double begin, double end) {
    libtraciPINVOKE.Vehicle_subscribeLeader__SWIG_0(vehID, dist, begin, end);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeLeader(string vehID, double dist, double begin) {
    libtraciPINVOKE.Vehicle_subscribeLeader__SWIG_1(vehID, dist, begin);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeLeader(string vehID, double dist) {
    libtraciPINVOKE.Vehicle_subscribeLeader__SWIG_2(vehID, dist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void subscribeLeader(string vehID) {
    libtraciPINVOKE.Vehicle_subscribeLeader__SWIG_3(vehID);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterLanes(IntVector lanes, bool noOpposite, double downstreamDist, double upstreamDist) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterLanes__SWIG_0(IntVector.getCPtr(lanes), noOpposite, downstreamDist, upstreamDist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterLanes(IntVector lanes, bool noOpposite, double downstreamDist) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterLanes__SWIG_1(IntVector.getCPtr(lanes), noOpposite, downstreamDist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterLanes(IntVector lanes, bool noOpposite) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterLanes__SWIG_2(IntVector.getCPtr(lanes), noOpposite);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterLanes(IntVector lanes) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterLanes__SWIG_3(IntVector.getCPtr(lanes));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterNoOpposite() {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterNoOpposite();
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterDownstreamDistance(double dist) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterDownstreamDistance(dist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterUpstreamDistance(double dist) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterUpstreamDistance(dist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterCFManeuver(double downstreamDist, double upstreamDist) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterCFManeuver__SWIG_0(downstreamDist, upstreamDist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterCFManeuver(double downstreamDist) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterCFManeuver__SWIG_1(downstreamDist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterCFManeuver() {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterCFManeuver__SWIG_2();
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterLCManeuver(int direction, bool noOpposite, double downstreamDist, double upstreamDist) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterLCManeuver__SWIG_0(direction, noOpposite, downstreamDist, upstreamDist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterLCManeuver(int direction, bool noOpposite, double downstreamDist) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterLCManeuver__SWIG_1(direction, noOpposite, downstreamDist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterLCManeuver(int direction, bool noOpposite) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterLCManeuver__SWIG_2(direction, noOpposite);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterLCManeuver(int direction) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterLCManeuver__SWIG_3(direction);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterLCManeuver() {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterLCManeuver__SWIG_4();
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterLeadFollow(IntVector lanes) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterLeadFollow(IntVector.getCPtr(lanes));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterTurn(double downstreamDist, double foeDistToJunction) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterTurn__SWIG_0(downstreamDist, foeDistToJunction);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterTurn(double downstreamDist) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterTurn__SWIG_1(downstreamDist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterTurn() {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterTurn__SWIG_2();
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterVClass(StringVector vClasses) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterVClass(StringVector.getCPtr(vClasses));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterVType(StringVector vTypes) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterVType(StringVector.getCPtr(vTypes));
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterFieldOfVision(double openingAngle) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterFieldOfVision(openingAngle);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterLateralDistance(double lateralDist, double downstreamDist, double upstreamDist) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterLateralDistance__SWIG_0(lateralDist, downstreamDist, upstreamDist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterLateralDistance(double lateralDist, double downstreamDist) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterLateralDistance__SWIG_1(lateralDist, downstreamDist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void addSubscriptionFilterLateralDistance(double lateralDist) {
    libtraciPINVOKE.Vehicle_addSubscriptionFilterLateralDistance__SWIG_2(lateralDist);
    if (libtraciPINVOKE.SWIGPendingException.Pending) throw libtraciPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
