# SUMO Native Controller Configuration
env: sumo

env_args:
  map_path: "maps/connaught_place.net.xml"
  cfg_path: "maps/connaught_place.sumocfg"
  step_length: 1.0
  decision_interval: 5
  episode_limit: 720
  use_gui: False
  max_lanes: 8

# In native mode, we don't control the traffic lights
control_tls: False