//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Eclipse.Sumo.Libsumo {

public class StringDoublePairVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<StringDoublePair>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal StringDoublePairVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(StringDoublePairVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(StringDoublePairVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~StringDoublePairVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libsumoPINVOKE.delete_StringDoublePairVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public StringDoublePairVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (StringDoublePair element in c) {
      this.Add(element);
    }
  }

  public StringDoublePairVector(global::System.Collections.Generic.IEnumerable<StringDoublePair> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (StringDoublePair element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public StringDoublePair this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(StringDoublePair[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(StringDoublePair[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, StringDoublePair[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public StringDoublePair[] ToArray() {
    StringDoublePair[] array = new StringDoublePair[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<StringDoublePair> global::System.Collections.Generic.IEnumerable<StringDoublePair>.GetEnumerator() {
    return new StringDoublePairVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new StringDoublePairVectorEnumerator(this);
  }

  public StringDoublePairVectorEnumerator GetEnumerator() {
    return new StringDoublePairVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class StringDoublePairVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<StringDoublePair>
  {
    private StringDoublePairVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public StringDoublePairVectorEnumerator(StringDoublePairVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public StringDoublePair Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (StringDoublePair)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public StringDoublePairVector() : this(libsumoPINVOKE.new_StringDoublePairVector__SWIG_0(), true) {
  }

  public StringDoublePairVector(StringDoublePairVector other) : this(libsumoPINVOKE.new_StringDoublePairVector__SWIG_1(StringDoublePairVector.getCPtr(other)), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    libsumoPINVOKE.StringDoublePairVector_Clear(swigCPtr);
  }

  public void Add(StringDoublePair x) {
    libsumoPINVOKE.StringDoublePairVector_Add(swigCPtr, StringDoublePair.getCPtr(x));
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = libsumoPINVOKE.StringDoublePairVector_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = libsumoPINVOKE.StringDoublePairVector_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = libsumoPINVOKE.StringDoublePairVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    libsumoPINVOKE.StringDoublePairVector_reserve(swigCPtr, n);
  }

  public StringDoublePairVector(int capacity) : this(libsumoPINVOKE.new_StringDoublePairVector__SWIG_2(capacity), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  private StringDoublePair getitemcopy(int index) {
    StringDoublePair ret = new StringDoublePair(libsumoPINVOKE.StringDoublePairVector_getitemcopy(swigCPtr, index), true);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private StringDoublePair getitem(int index) {
    StringDoublePair ret = new StringDoublePair(libsumoPINVOKE.StringDoublePairVector_getitem(swigCPtr, index), false);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, StringDoublePair val) {
    libsumoPINVOKE.StringDoublePairVector_setitem(swigCPtr, index, StringDoublePair.getCPtr(val));
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(StringDoublePairVector values) {
    libsumoPINVOKE.StringDoublePairVector_AddRange(swigCPtr, StringDoublePairVector.getCPtr(values));
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public StringDoublePairVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = libsumoPINVOKE.StringDoublePairVector_GetRange(swigCPtr, index, count);
    StringDoublePairVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new StringDoublePairVector(cPtr, true);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, StringDoublePair x) {
    libsumoPINVOKE.StringDoublePairVector_Insert(swigCPtr, index, StringDoublePair.getCPtr(x));
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, StringDoublePairVector values) {
    libsumoPINVOKE.StringDoublePairVector_InsertRange(swigCPtr, index, StringDoublePairVector.getCPtr(values));
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    libsumoPINVOKE.StringDoublePairVector_RemoveAt(swigCPtr, index);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    libsumoPINVOKE.StringDoublePairVector_RemoveRange(swigCPtr, index, count);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public static StringDoublePairVector Repeat(StringDoublePair value, int count) {
    global::System.IntPtr cPtr = libsumoPINVOKE.StringDoublePairVector_Repeat(StringDoublePair.getCPtr(value), count);
    StringDoublePairVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new StringDoublePairVector(cPtr, true);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    libsumoPINVOKE.StringDoublePairVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    libsumoPINVOKE.StringDoublePairVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, StringDoublePairVector values) {
    libsumoPINVOKE.StringDoublePairVector_SetRange(swigCPtr, index, StringDoublePairVector.getCPtr(values));
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
