//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Eclipse.Sumo.Libsumo {

public class TraCIStage : TraCIResult {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal TraCIStage(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libsumoPINVOKE.TraCIStage_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TraCIStage obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          libsumoPINVOKE.delete_TraCIStage(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public TraCIStage(int type, string vType, string line, string destStop, StringVector edges, double travelTime, double cost, double length, string intended, double depart, double departPos, double arrivalPos, string description) : this(libsumoPINVOKE.new_TraCIStage__SWIG_0(type, vType, line, destStop, StringVector.getCPtr(edges), travelTime, cost, length, intended, depart, departPos, arrivalPos, description), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIStage(int type, string vType, string line, string destStop, StringVector edges, double travelTime, double cost, double length, string intended, double depart, double departPos, double arrivalPos) : this(libsumoPINVOKE.new_TraCIStage__SWIG_1(type, vType, line, destStop, StringVector.getCPtr(edges), travelTime, cost, length, intended, depart, departPos, arrivalPos), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIStage(int type, string vType, string line, string destStop, StringVector edges, double travelTime, double cost, double length, string intended, double depart, double departPos) : this(libsumoPINVOKE.new_TraCIStage__SWIG_2(type, vType, line, destStop, StringVector.getCPtr(edges), travelTime, cost, length, intended, depart, departPos), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIStage(int type, string vType, string line, string destStop, StringVector edges, double travelTime, double cost, double length, string intended, double depart) : this(libsumoPINVOKE.new_TraCIStage__SWIG_3(type, vType, line, destStop, StringVector.getCPtr(edges), travelTime, cost, length, intended, depart), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIStage(int type, string vType, string line, string destStop, StringVector edges, double travelTime, double cost, double length, string intended) : this(libsumoPINVOKE.new_TraCIStage__SWIG_4(type, vType, line, destStop, StringVector.getCPtr(edges), travelTime, cost, length, intended), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIStage(int type, string vType, string line, string destStop, StringVector edges, double travelTime, double cost, double length) : this(libsumoPINVOKE.new_TraCIStage__SWIG_5(type, vType, line, destStop, StringVector.getCPtr(edges), travelTime, cost, length), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIStage(int type, string vType, string line, string destStop, StringVector edges, double travelTime, double cost) : this(libsumoPINVOKE.new_TraCIStage__SWIG_6(type, vType, line, destStop, StringVector.getCPtr(edges), travelTime, cost), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIStage(int type, string vType, string line, string destStop, StringVector edges, double travelTime) : this(libsumoPINVOKE.new_TraCIStage__SWIG_7(type, vType, line, destStop, StringVector.getCPtr(edges), travelTime), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIStage(int type, string vType, string line, string destStop, StringVector edges) : this(libsumoPINVOKE.new_TraCIStage__SWIG_8(type, vType, line, destStop, StringVector.getCPtr(edges)), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIStage(int type, string vType, string line, string destStop) : this(libsumoPINVOKE.new_TraCIStage__SWIG_9(type, vType, line, destStop), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIStage(int type, string vType, string line) : this(libsumoPINVOKE.new_TraCIStage__SWIG_10(type, vType, line), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIStage(int type, string vType) : this(libsumoPINVOKE.new_TraCIStage__SWIG_11(type, vType), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIStage(int type) : this(libsumoPINVOKE.new_TraCIStage__SWIG_12(type), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public TraCIStage() : this(libsumoPINVOKE.new_TraCIStage__SWIG_13(), true) {
    if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
  }

  public int type {
    set {
      libsumoPINVOKE.TraCIStage_type_set(swigCPtr, value);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = libsumoPINVOKE.TraCIStage_type_get(swigCPtr);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string vType {
    set {
      libsumoPINVOKE.TraCIStage_vType_set(swigCPtr, value);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = libsumoPINVOKE.TraCIStage_vType_get(swigCPtr);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string line {
    set {
      libsumoPINVOKE.TraCIStage_line_set(swigCPtr, value);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = libsumoPINVOKE.TraCIStage_line_get(swigCPtr);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string destStop {
    set {
      libsumoPINVOKE.TraCIStage_destStop_set(swigCPtr, value);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = libsumoPINVOKE.TraCIStage_destStop_get(swigCPtr);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public StringVector edges {
    set {
      libsumoPINVOKE.TraCIStage_edges_set(swigCPtr, StringVector.getCPtr(value));
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = libsumoPINVOKE.TraCIStage_edges_get(swigCPtr);
      StringVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new StringVector(cPtr, false);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double travelTime {
    set {
      libsumoPINVOKE.TraCIStage_travelTime_set(swigCPtr, value);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = libsumoPINVOKE.TraCIStage_travelTime_get(swigCPtr);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double cost {
    set {
      libsumoPINVOKE.TraCIStage_cost_set(swigCPtr, value);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = libsumoPINVOKE.TraCIStage_cost_get(swigCPtr);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double length {
    set {
      libsumoPINVOKE.TraCIStage_length_set(swigCPtr, value);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = libsumoPINVOKE.TraCIStage_length_get(swigCPtr);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string intended {
    set {
      libsumoPINVOKE.TraCIStage_intended_set(swigCPtr, value);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = libsumoPINVOKE.TraCIStage_intended_get(swigCPtr);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double depart {
    set {
      libsumoPINVOKE.TraCIStage_depart_set(swigCPtr, value);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = libsumoPINVOKE.TraCIStage_depart_get(swigCPtr);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double departPos {
    set {
      libsumoPINVOKE.TraCIStage_departPos_set(swigCPtr, value);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = libsumoPINVOKE.TraCIStage_departPos_get(swigCPtr);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double arrivalPos {
    set {
      libsumoPINVOKE.TraCIStage_arrivalPos_set(swigCPtr, value);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = libsumoPINVOKE.TraCIStage_arrivalPos_get(swigCPtr);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string description {
    set {
      libsumoPINVOKE.TraCIStage_description_set(swigCPtr, value);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = libsumoPINVOKE.TraCIStage_description_get(swigCPtr);
      if (libsumoPINVOKE.SWIGPendingException.Pending) throw libsumoPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}

}
